name: Push emacs-client to DockerHub
on:
  push:
    branches:
      - "0.12"
jobs:
  push_emacs_client:
    name: Push emacs-learn-ocaml-client image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get branch name
        run: branch="${{ github.ref }}"; echo "::set-output name=branch::${branch#refs/heads/}"
        id: branch
      - name: Push to Docker Hub
        # https://github.com/docker/build-push-action/tree/releases/v1#readme
        uses: docker/build-push-action@v1
        with:
          # path: ci/docker-emacs-learn-ocaml-client
          build_args: "base=ocamlsf/learn-ocaml-client,version=${{ steps.branch.outputs.branch }}"
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=${{ steps.branch.outputs.branch }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # repository: ocamlsf/learn-ocaml
          repository: pfitaxel/emacs-learn-ocaml-client
          tags: ${{ steps.branch.outputs.branch }}
